/**
 * CDI integration of Dirac for the Vauban container.
 *
 * <p>Planned components (see ROADMAP.md M1+) :</p>
 * <ul>
 *   <li>{@code CountedInterceptor} — CDI {@code @Interceptor} with priority 4020
 *       for {@code @Counted}.</li>
 *   <li>{@code TimedInterceptor} — CDI {@code @Interceptor} with priority 4021
 *       for {@code @Timed}.</li>
 *   <li>{@code DiracExtension} — Vauban BCE {@code BuildCompatibleExtension}: resolves
 *       {@code @Gauge} at startup via {@code MethodHandle}, validates signatures,
 *       populates the BASE registry (JVM metrics).</li>
 *   <li>{@code MetricRegistryProducerBean} — produces the three {@code MetricRegistry}
 *       ({@code APPLICATION}, {@code BASE}, {@code VENDOR}) as {@code @ApplicationScoped}
 *       beans with the {@code @RegistryScope} qualifier.</li>
 * </ul>
 *
 * <p><strong>JPMS note — testCompile workaround</strong> :
 * {@code module-info.java} is in {@code src/main/module-info/} to prevent Maven
 * Compiler Plugin from detecting JPMS during {@code testCompile} (vauban-core is test-scope,
 * absent from {@code target/javamodules/}).
 * See {@code dirac-core/pom.xml} for the full workaround description.</p>
 */
module io.vidocq.dirac.cdi.vauban {
    requires transitive io.vidocq.dirac.core;

    requires static jakarta.cdi;
    requires static jakarta.inject;
    requires static jakarta.annotation;
    requires static jakarta.interceptor;
    // Compile-only (optional at runtime): supplies the VaubanComponentProvider service type.
    requires static io.vidocq.vauban.api;

    exports io.vidocq.dirac.cdi.internal;
    // In-module instantiation, field injection and producer-method invocation of this package's
    // beans (generated by the Vauban APT as _VaubanComponents). The qualified open below stays
    // because the interceptor @AroundInvoke methods (CountedInterceptor/TimedInterceptor) are still
    // invoked reflectively — routing them in-module is deferred (the VaubanComponentProvider.invoke
    // SPI has no `throws` while @AroundInvoke declares `throws Exception`).
    opens io.vidocq.dirac.cdi.internal to io.vidocq.vauban.core;

    // Dirac BCE: @Gauge resolution + BASE registry population at startup
    provides jakarta.enterprise.inject.build.compatible.spi.BuildCompatibleExtension
            with io.vidocq.dirac.cdi.internal.DiracExtension;
    // In-module component provider generated by the APT (create/injectField/invoke).
    provides io.vidocq.vauban.api.VaubanComponentProvider
            with io.vidocq.dirac.cdi.internal._VaubanComponents;
}
