/**
 * CDI integration of Dirac for the Vauban container.
 *
 * <p>Planned components (see ROADMAP.md M1+) :</p>
 * <ul>
 *   <li>{@code CountedInterceptor} — CDI {@code @Interceptor} with priority 4020
 *       for {@code @Counted}.</li>
 *   <li>{@code TimedInterceptor} — CDI {@code @Interceptor} with priority 4021
 *       for {@code @Timed}.</li>
 *   <li>{@code DiracExtension} — Vauban BCE {@code BuildCompatibleExtension}: resolves
 *       {@code @Gauge} at startup via {@code MethodHandle}, validates signatures,
 *       populates the BASE registry (JVM metrics).</li>
 *   <li>{@code MetricRegistryProducerBean} — produces the three {@code MetricRegistry}
 *       ({@code APPLICATION}, {@code BASE}, {@code VENDOR}) as {@code @ApplicationScoped}
 *       beans with the {@code @RegistryScope} qualifier.</li>
 * </ul>
 *
 * <p><strong>JPMS note — testCompile workaround</strong> :
 * {@code module-info.java} is in {@code src/main/module-info/} to prevent Maven
 * Compiler Plugin from detecting JPMS during {@code testCompile} (vauban-core is test-scope,
 * absent from {@code target/javamodules/}).
 * See {@code dirac-core/pom.xml} for the full workaround description.</p>
 */
module io.vidocq.dirac.cdi.vauban {
    requires transitive io.vidocq.dirac.core;

    requires static jakarta.cdi;
    requires static jakarta.inject;
    requires static jakarta.annotation;
    requires static jakarta.interceptor;
    // Compile-only (optional at runtime): supplies the VaubanComponentProvider service type.
    requires static io.vidocq.vauban.api;

    exports io.vidocq.dirac.cdi.internal;
    // No `opens` to io.vidocq.vauban.core: this package's beans (and the CountedInterceptor/
    // TimedInterceptor classes themselves, since VAU-INT-004) are instantiated and field-injected
    // in-module by the Vauban-APT-generated _VaubanComponents provider, and the interceptors'
    // @AroundConstruct/@AroundInvoke methods are public in this exported package, so the container
    // reaches them without privateLookupIn. Proven on the strict module path by
    // dirac-cdi-vauban-jpms-it (both interception kinds, zero opens).

    // Dirac BCE: @Gauge resolution + BASE registry population at startup
    provides jakarta.enterprise.inject.build.compatible.spi.BuildCompatibleExtension
            with io.vidocq.dirac.cdi.internal.DiracExtension;
    // In-module component provider generated by the APT (create/injectField/invoke).
    provides io.vidocq.vauban.api.VaubanComponentProvider
            with io.vidocq.dirac.cdi.internal._VaubanComponents;
}
