/*
 * Copyright (c) 2026 Yann Blazart, Antoine Sabot-Durand and the Vidocq contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License, v. 2.0 are satisfied: GNU General Public License, version 2
 * or any later version, which is available at
 * https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 *
 * It is also made available under the European Union Public Licence v. 1.2,
 * which is available at
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * SPDX-License-Identifier: EPL-2.0 OR EUPL-1.2 OR GPL-2.0-or-later
 */
package io.vidocq.dirac.cdi.jpmsit;

import io.vidocq.dirac.cdi.internal.CountedInterceptor;
import io.vidocq.dirac.cdi.internal.GaugeRegistrationBean;
import io.vidocq.dirac.cdi.internal.MetricRegistryProducerBean;
import io.vidocq.dirac.cdi.internal.TimedInterceptor;
import io.vidocq.vauban.core.container.VaubanContainer;
import org.eclipse.microprofile.metrics.MetricID;
import org.eclipse.microprofile.metrics.MetricRegistry;
import org.eclipse.microprofile.metrics.Tag;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

/**
 * Runs on the MODULE PATH (this is a named module with a {@code module-info}). It boots a Vauban
 * container programmatically and obtains the {@code @Counted} bean via {@link
 * VaubanContainer#select(Class)} — deliberately NOT through {@code @Inject} into the test instance,
 * so nothing reflects into the test class and the module needs no {@code opens}.
 *
 * <p>What this proves, that a class-path test cannot: {@code @Counted} interception fires on a strict
 * module path with a BUILD-TIME generated {@code $$Intercepted} subclass and the generated
 * {@code VaubanComponentProvider}, with zero {@code opens} to {@code io.vidocq.vauban.core}. Both
 * interception kinds are exercised:
 * <ul>
 *   <li><b>{@code @AroundConstruct}</b> — the class-level {@code @Counted} makes the constructor an
 *       intercepted target, so {@code CountedInterceptor.aroundConstruct} runs in-module (the
 *       interceptor is instantiated by the generated provider — VAU-INT-004 — and its public
 *       lifecycle method is reachable without opens). That callback registers the counter;</li>
 *   <li><b>{@code @AroundInvoke}</b> — each {@link MetricsService#ping()} call increments it.</li>
 * </ul>
 */
class MetricsModulePathTest {

    @Test
    void counts_invocations_on_the_module_path_without_opens() throws Exception {
        // The $$Intercepted subclass is a BUILD-TIME class (generated by the APT), loadable by name.
        assertNotNull(
                Class.forName("io.vidocq.dirac.cdi.jpmsit.MetricsService$$Intercepted"),
                "the APT must have generated MetricsService$$Intercepted at build time");

        VaubanContainer container = VaubanContainer.builder()
                .addBeanClass(MetricRegistryProducerBean.class)
                .addBeanClass(GaugeRegistrationBean.class)
                .addBeanClass(CountedInterceptor.class)
                .addBeanClass(TimedInterceptor.class)
                .addBeanClass(MetricsService.class)
                .build();
        try {
            MetricsService svc = container.select(MetricsService.class);
            assertEquals("pong", svc.ping());
            assertEquals("pong", svc.ping());

            MetricRegistryProducerBean producer = container.select(MetricRegistryProducerBean.class);
            MetricRegistry registry = producer.registry(MetricRegistry.APPLICATION_SCOPE);
            var metricId = new MetricID("jpmsit.counted.calls", new Tag("source", "jpms"));
            assertNotNull(registry.getCounter(metricId),
                    "the @AroundConstruct callback must have pre-registered the counter in-module, no opens");
            assertEquals(2L, registry.getCounter(metricId).getCount(),
                    "the @Counted interceptor must count both calls, in-module, with no opens");
        } finally {
            container.close();
        }
    }
}
