/*
 * Copyright (c) 2026 Yann Blazart, Antoine Sabot-Durand and the Vidocq contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License, v. 2.0 are satisfied: GNU General Public License, version 2
 * or any later version, which is available at
 * https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 *
 * It is also made available under the European Union Public Licence v. 1.2,
 * which is available at
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * SPDX-License-Identifier: EPL-2.0 OR EUPL-1.2 OR GPL-2.0-or-later
 */
/**
 * CDI integration of Dirac for the Vauban container.
 *
 * <p>Planned components (see ROADMAP.md M1+) :</p>
 * <ul>
 *   <li>{@code CountedInterceptor} — CDI {@code @Interceptor} with priority 4020
 *       for {@code @Counted}.</li>
 *   <li>{@code TimedInterceptor} — CDI {@code @Interceptor} with priority 4021
 *       for {@code @Timed}.</li>
 *   <li>{@code DiracExtension} — Vauban BCE {@code BuildCompatibleExtension}: resolves
 *       {@code @Gauge} at startup via {@code MethodHandle}, validates signatures,
 *       populates the BASE registry (JVM metrics).</li>
 *   <li>{@code MetricRegistryProducerBean} — produces the three {@code MetricRegistry}
 *       ({@code APPLICATION}, {@code BASE}, {@code VENDOR}) as {@code @ApplicationScoped}
 *       beans with the {@code @RegistryScope} qualifier.</li>
 * </ul>
 */
module io.vidocq.dirac.cdi.vauban {
    requires transitive io.vidocq.dirac.core;

    requires static jakarta.cdi;
    requires static jakarta.inject;
    requires static jakarta.annotation;
    requires static jakarta.interceptor;
    // Compile-only (optional at runtime): supplies the VaubanComponentProvider service type.
    requires static io.vidocq.vauban.api;

    exports io.vidocq.dirac.cdi.internal;
    // No `opens` to io.vidocq.vauban.core: this package's beans (and the CountedInterceptor/
    // TimedInterceptor classes themselves, since VAU-INT-004) are instantiated and field-injected
    // in-module by the Vauban-APT-generated _VaubanComponents provider, and the interceptors'
    // @AroundConstruct/@AroundInvoke methods are public in this exported package, so the container
    // reaches them without privateLookupIn. Proven on the strict module path by
    // dirac-cdi-vauban-module-it (both interception kinds, zero opens).

    // Dirac BCE: @Gauge resolution + BASE registry population at startup
    provides jakarta.enterprise.inject.build.compatible.spi.BuildCompatibleExtension
            with io.vidocq.dirac.cdi.internal.DiracExtension;
    // In-module component provider generated by the APT (create/injectField/invoke).
    provides io.vidocq.vauban.api.VaubanComponentProvider
            with io.vidocq.dirac.cdi.internal._VaubanComponents;

    //CG-05 — generated $$DiracMetrics companions (dirac annotation processor):
    //strict Java Modules user modules declare `provides MetricsCompanion with ...`.
    uses io.vidocq.dirac.spi.gen.MetricsCompanion;
}
